### ISSUE TITLE
this.timestamp is undefined :/

### ISSUE THREAD

**Issue by jdsharp** [LeanKit-Labs/sliver#1]
I've run into a situation where I receive this error. It appears to occur randomly, but with greater than 50% frequency.

Relevant code:

```
var sliverFactory = require('sliver');

function foo() {
    this.sliver = sliverFactory(this.config.seed); // seed is 'An arbitrary string of some characters'
}

foo.prototype.bar = function() {
    return {
        id: this.sliver.getId(),
        versionId: this.sliver.getId()
    };
};

var f = new foo();
foo.bar();
```

./node_modules/sliver/src/sliver.js:77

```
    var bytes = this.timestamp.concat( this.seed, this.msBytes ).reverse();
                               ^
TypeError: Cannot call method 'concat' of undefined
    at Flakey.getId (./dev/node_modules/sliver/src/sliver.js:77:29)
```

**Comment by arobson** [comment]
@jdsharp - hey man, sorry I hadn't seen this until now. Is this with the latest version that's on NPM (0.1.0)? Also, what version of Node are you seeing this on? Asking b/c the test suite generates several thousand of these back-to-back and I haven't seen this error come up before.

I've also changed it so that it will derive a unique seed from the MAC or host name + the PID. Should guarantee uniqueness without having to worry about it (unless you have multiple machines in your datacenter with identical MACs/host names)

**Comment by jdsharp** [comment]
@arobson hey! So I had been using 0.0.5 with node 0.10.36. I think the issue surrounds when I call the silverFactory method in my constructor. When I instead do `require('sliver')();` It then works fine (I like the hostname + pid as the seed, anything to avoid the async ready call :)
